routes/web.php
<?php

use App\Http\Controllers\DownloadedVideoController;
use App\Http\Controllers\ExecutionController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\QueueController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return redirect()->route('jobs.all');
})->name('home');
Route::get('/jobs/failed', [ExecutionController::class, 'listFailed'])->name('jobs.failed');
Route::get('/jobs/successful', [ExecutionController::class, 'listSuccessful'])->name('jobs.successful');
Route::get('/jobs/all', [ExecutionController::class, 'listAll'])->name('jobs.all');
Route::post('/jobs/clear', [ExecutionController::class, 'clear'])->name('jobs.clear');
Route::post('/jobs/{id}/delete', [ExecutionController::class, 'delete'])->name('jobs.delete');

Route::get('/videos', [DownloadedVideoController::class, 'list'])->name('videos.list');

Route::get('/queue', [QueueController::class, 'list'])->name('queue.list');

app/Models/DownloadedVideo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class DownloadedVideo extends Model
{
    protected $table = 'downloaded_videos';
    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'execution_id',
        'video_id',
        'content_id',
        'title',
        'slug',
        'content_created_at',
        'download_url',
        'description',
        'filesize'
    ];
}

app/Models/ExecutionLog.php
<?php

namespace App\Models;

use App\Enums\ExecutionStatus;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class ExecutionLog extends Model
{
    protected $table = 'execution_log';
    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */

    public $timestamps = false;

    protected $fillable = [
        'status',
        'success_count',
        'start_timestamp',
        'current_file',
        'current_file_progress',
        'completed_timestamp',
    ];

    protected $casts = [
        'status' => ExecutionStatus::class
    ];

    protected function scopeProcessing($query)
    {
        return $query->where('status', ExecutionStatus::PROCESSING);
    }

    public function getStartedAttribute()
    {
        return Carbon::parse($this->start_timestamp)->toDateTimeString();
    }
}

app/Models/QueuedVideo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class QueuedVideo extends Model
{
    protected $table = 'download_queue';

    public $timestamps = false;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'status',
        'show',
        'episode',
        'video_id',
        'content_id',
        'title',
        'slug',
        'download_url',
        'current_download_percentage',
        'description',
        'content_created_at'
    ];
}

app/Models/RemoteCheckLog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class RemoteCheckLog extends Model
{
    protected $table = 'remote_check_log';
    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */

    public $timestamps = false;

    protected $fillable = [
        'data_last_fetched',
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DownloadedVideoController.php
<?php

namespace App\Http\Controllers;

use App\Models\DownloadedVideo;

class DownloadedVideoController extends Controller
{
    public function list()
    {
        return view('videos/list', ['videos' => DownloadedVideo::all()]);
    }
}

app/Http/Controllers/ExecutionController.php
<?php

namespace App\Http\Controllers;

use App\Models\ExecutionLog;
use App\Enums\ExecutionStatus;

class ExecutionController extends Controller
{
    public function list(ExecutionStatus $status = null)
    {
        return view('executions.running', ['executions' => ExecutionLog::where('status', $status)->orderByDesc('start_timestamp')->take(15)->get()]);
    }
    public function listRunning()
    {
        return $this->list(ExecutionStatus::PROCESSING);
    }
    public function listFailed()
    {
        return $this->list(ExecutionStatus::FAILED);
    }
    public function listSuccessful()
    {
        return $this->list(ExecutionStatus::SUCCESS);
    }
    public function listAll()
    {
        return view('executions.running', ['executions' => ExecutionLog::orderByDesc('start_timestamp')->take(15)->get()]);
    }

    public function delete(ExecutionLog $id)
    {
        $id->delete();
        return back();
    }

    public function clear()
    {
        ExecutionLog::truncate();
        return back();
    }

    public function running()
    {
        return ExecutionLog::processing()->get();
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Models\DownloadedVideo;
use Illuminate\Support\Facades\Route;

class HomeController extends Controller
{
    public function list()
    {
        $routes = Route::getRoutes();
        foreach ($routes as $route) {
            dd($route->getName());
        };
        return view('videos/list', ['videos' => DownloadedVideo::all()]);
    }
}

app/Http/Controllers/QueueController.php
<?php

namespace App\Http\Controllers;

use App\Models\QueuedVideo;

class QueueController extends Controller
{
    public function list()
    {
        return view('queue/list', ['queued' => QueuedVideo::all()]);
    }
}

resources/views/executions/running.blade.php
@extends('template')

@section('page-title')
Abundance+ Downloads
@endsection

@section('head-append')
<script type="text/javascript">
function deleteLog(id){
    axios.post(`/jobs/${id}/delete`).then((resp)=>{
        window.location.reload();
    });
}
function clearLogs(){
    axios.post(`/jobs/clear`).then((resp)=>{
        window.location.reload();
    });
}
</script>
@endsection

@section('content')
<div class="container-fluid p-4">
    @if($executions->count() == 0)
    <h1 class="text-center">No Jobs Running</h1>
    @else
    <h1 class="text-center">Running Jobs
        <button type="button" class="btn" onclick="clearLogs()">Clear</button>
    </h1>
    <table class="table">
        <thead>
            <tr>
              <th scope="col">ID</th>
              <th scope="col">Current File</th>
              <th scope="col">Progress</th>
              <th scope="col">Execution Status</th>
              <th scope="col">Message</th>
              <th scope="col">Timestamp</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
        @foreach($executions as $execution)
        <tr>
            <th scope="row">{{$execution->id}}</th>
            <td>{{$execution->current_file}}</td>
            <td width="15%">
                <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: {{$execution->current_file_percentage}}%" aria-valuenow="{{$execution->current_file_percentage}}" aria-valuemin="0" aria-valuemax="100">{{$execution->current_file_percentage ?? 0}}%</div>
                  </div>
            </td>
            <td id="execution-{{$execution->id}}-pct"><span class="badge bg-{{$execution->status->colorClass()}}">{{$execution->status->string()}}</span></td>
            <td>{{$execution->message}}</td>
            <td>{{$execution->started}}</td>
            <td width="2rem">
                <button type="button" class="btn-close" aria-label="Close" onclick="deleteLog({{$execution->id}})"></button>
            </td>
        </tr>
        @endforeach
          </tbody>
    </table>
    @endif
</div>

@endsection

resources/views/head.blade.php
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>@yield('page-title')</title>
<!-- Fonts -->
<link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap" rel="stylesheet">
<script src="{{ asset('js/app.js') }}"></script>
<link rel="stylesheet" href="{{asset('css/app.css')}}">

resources/views/queue/list.blade.php
@extends('template')

@section('page-title')
Abundance+ Downloaded Videos
@endsection

@section('head-extend')

@endsection

@section('content')
<div class="container p-4">
    @if($queued->count() == 0)
    <h1 class="text-center">No Videos Queued</h1>
    @else
    <h1 class="text-center">Queued Videos</h1>
    <table class="table">
        <thead>
            <tr>
              <th scope="col">ID</th>
              <th scope="col">Show</th>
              <th scope="col">Title</th>
              <th scope="col">Description</th>
            </tr>
          </thead>
          <tbody>
        @foreach($queued as $video)
        <tr>
            <th scope="row">{{$video->id}}</th>
            <td>{{$video->title}}</td>
            <td>{{$video->slug}}</td>
            <td>
                {{strlen($video->description) > 200 ? substr($video->description,0,200)."..." : $video->description}}
            </td>
        </tr>
        @endforeach
          </tbody>
    </table>
    @endif
</div>
@endsection

resources/views/template.blade.php
<!doctype html>
<html lang="en">
  <head>
    @include('head')
    @yield('head-append')
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a href="{{route('jobs.all')}}" class="nav-link">Job Log</a>
            </li>
            <li class="nav-item">
                <a href="{{route('videos.list')}}" class="nav-link">Downloaded Videos</a>
            </li>
            <li class="nav-item">
                <a href="{{route('queue.list')}}" class="nav-link">Queued Videos</a>
            </li>
        </ul>
    </div>
    </nav>
    @yield('content')
  </body>
</html>

resources/views/videos/list.blade.php
@extends('template')

@section('page-title')
Abundance+ Downloaded Videos
@endsection

@section('head-extend')

@endsection

@section('content')
<div class="container p-4">
    @if($videos->count() == 0)
    <h1 class="text-center">No Videos Downloaded</h1>
    @else
    <h1 class="text-center">Downloaded Videos</h1>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Title</th>
                <th scope="col">Slug</th>
                <th scope="col">Description</th>
            </tr>
          </thead>
          <tbody>
        @foreach($videos as $video)
        <tr>
            <th scope="row">{{$video->id}}</th>
            <td>{{$video->title}}</td>
            <td>{{$video->slug}}</td>
            <td>
                {{strlen($video->description) > 200 ? substr($video->description,0,200)."..." : $video->description}}
            </td>
        </tr>
        @endforeach
          </tbody>
    </table>
    @endif
</div>
@endsection